# : Manager [[[

[mgr]
cwd = { fg = "#dee3e5" }

# Tab
tab_active = { fg = "#00363f", bg = "#83d2e5", bold = true }
tab_inactive = { fg = "#a6eeff", bg = "#001f25" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#768aff", bg = "#768aff" }
marker_cut = { fg = "#dce1ff", bg = "#dce1ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#bdc5eb", bg = "#bdc5eb" }

# Count
count_copied = { fg = "#111a37", bg = "#dce1ff" }
count_cut = { fg = "#111a37", bg = "#dce1ff" }
count_selected = { fg = "#00363f", bg = "#bdc5eb" }

# Border
border_symbol = " "
border_style  = { fg = "#83d2e5" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00363f", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#83d2e5", fg = "#00363f", bold = true }
normal_alt  = { bg = "#3f484b", fg = "#bfc8cb" }

# Select mode
select_main = { bg = "#b2cbd2", fg = "#1c3439", bold = true }
select_alt  = { bg = "#3f484b", fg = "#bfc8cb" }

# Unset mode
unset_main = { bg = "#bdc5eb", fg = "#272f4d", bold = true }
unset_alt  = { bg = "#3f484b", fg = "#bfc8cb" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#83d2e5", bg = "#343a3c" }
progress_error = { fg = "#ffb4ab", bg = "#343a3c" }

# Permissions
permissions_t = { fg = "#578794" }
permissions_w = { fg = "#485ec7" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#435eff" }
permissions_s = { fg = "#0dd1ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#83d2e5" }
active = { fg = "#bdc5eb", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#83d2e5" }
value = { fg = "#dee3e5" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#83d2e5", bold = true, bg = "#0e1416" }
inactive = { fg = "#b2cbd2", bg = "#0e1416" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#83d2e5", bg = "#00363f" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#83d2e5" }
title = {}
hovered = { fg = "#dce1ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3c" }
cand = { fg = "#83d2e5" }
rest = { fg = "#00363f" }
desc = { fg = "#dee3e5" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dee3e5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dee3e5" }
run = { fg = "#dee3e5" }
footer = { fg = "#1c3439", bg = "#b2cbd2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#bdc5eb" }
title_warn = { fg = "#83d2e5" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dee3e5" },
    { name = "*/", fg = "#83d2e5" },
]

# : ]]]
